### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by flowflow** [foxip/mollie-api-csharp#3]
I downloaded the zip, but when I try to build it in Visual Studio 2013 I get these errors:

Metadata file 'C:\mollie-api-csharp-master\Mollie.Api\bin\Debug\Mollie.Api.dll' could not be found	C:\mollie-api-csharp-master\Mollie.Tests\CSC	Mollie.Tests
Metadata file 'C:\mollie-api-csharp-master\Mollie.Api\bin\Debug\Mollie.Api.dll' could not be found	C:\mollie-api-csharp-master\Mollie.Example\CSC	Mollie.Example
Unable to locate 'C:\mollie-api-csharp-master\.nuget\NuGet.exe'	Mollie.Api

What am I missing?

**Comment by foxip** [comment]
Could you try to "enable nuget package restore", right click on the 
solution, and this will appear.

-- 
met vriendelijke groet,
Albert Vos



flowflow wrote:

**Comment by flowflow** [comment]
Thanks for getting back to me.
When I right-click the solution and click "enable nuget package restore"

I get the message: "Configuring the solution to restore NuGet packages on build..."

And after that the error: "An error occurred while configuring the solution to restore NuGet packages on build. The operation has timed out"

So now I still can't build...any other suggestions?

Thanks!

**Comment by WebstudioThomHubers** [comment]
Since this is more likely to be a NuGet problem I'd suggest you look for help in the NuGet section of StackOverflow. That increases your chances.

**Comment by flowflow** [comment]
You were right, NuGet services were down when I was trying to build it :)
