### ISSUE TITLE
Improper timeout for API calls

### ISSUE THREAD

**Issue by willemstuursma** [foxip/mollie-api-csharp#8]
Hi. 

I noticed that this library does not set a custom timeout. If I am not mistaken, that means that the default timeout of 100s is used.

A 100 second timeout for creating payments is inappropriate. A customer will not have that much patience.

The Mollie reference libraries use a 10s timeout. Could you add this to your library?

**Comment by foxip** [comment]
Yes, the default timeout is 100 seconds, I will change it to 10 seconds

**Comment by willemstuursma** [comment]
Thanks, that's great!
